# DataFrames II: Filtering Data

In [2]:
import pandas as pd

## This Module's Dataset + Memory Optimization

In [3]:
employees = pd.read_csv("employees.csv")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

- The `info` method shows a summary of the `DataFrame` including missing values and data types.

In [4]:
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    str
 1   Gender             855 non-null    str
 2   Start Date         1000 non-null   str
 3   Last Login Time    1000 non-null   str
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    str
dtypes: float64(1), int64(1), object(1), str(5)
memory usage: 98.3+ KB

- The `pd.to_datetime`function method converts a `Series` to hold datetime values.
- The `format` parameter informs pandas of the format that the times are stored in.
- We pass symbols designating the segments of the string. For example, `%m` is for month and `%d` is for day.
- Use the `astype` method to convert the values in a `Series` to another type.

In [5]:
# Notably, their example does not use astype....
# Format is the input's format, not your desired output
employees["Start Date"] = pd.to_datetime(employees["Start Date"], format="%m/%d/%Y")
employees["Start Date"].head()

0   1993-08-06
1   1996-03-31
2   1993-04-23
3   2005-03-04
4   1998-01-24
Name: Start Date, dtype: datetime64[us]

- The `dt` attribute reveals an object with many datetime-related attributes and methods.
- The `dt.time` attribute extracts only the time from each value in a datetime `Series`.

In [6]:
employees["Start Date"].head().dt.time

0    00:00:00
1    00:00:00
2    00:00:00
3    00:00:00
4    00:00:00
Name: Start Date, dtype: object

- Let's convert the `Senior Management` column into a Boolean column.
- Let's convert the `Gender` column into a category column.

In [7]:
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Senior Management"].head()

0     True
1     True
2    False
3     True
4     True
Name: Senior Management, dtype: bool

In [8]:
# This one still feels weird, as category doesn't seem like a type.
employees["Gender"] = employees["Gender"].astype("category")
employees["Gender"].head()

0      Male
1      Male
2    Female
3      Male
4      Male
Name: Gender, dtype: category
Categories (2, str): ['Female', 'Male']

## Filter A DataFrame  Based On A Condition
- Pandas needs a Boolean `Series` to perform a filter.
- Pass the Boolean `Series` inside square brackets after the `DataFrame`.

In [9]:
employees[employees["Gender"] == "Male"].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,6:53 AM,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,1:35 AM,115163,10.125,False,Legal

In [10]:
# Ok, very cool way to query the date data. First 5 employees hired after this date.
employees[employees["Start Date"] >= "2000-01-01"].sort_values("Start Date").head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
337,Earl,Male,2000-01-05,5:46 PM,91344,4.035,True,Sales
221,Gregory,Male,2000-01-29,6:01 AM,109564,3.845,False,Legal
810,Ralph,Male,2000-02-10,4:48 PM,89854,7.227,False,Business Development
26,Craig,Male,2000-02-27,7:45 AM,37598,7.757,True,Marketing
657,Rebecca,Female,2000-03-05,10:33 AM,46750,11.367,True,Sales

In [11]:
# Can even query on multiple things, but use bitwise operator and parentheses
employees[
  (employees["Start Date"] >= "2000-01-01") & 
  (employees["Gender"] != "Male")
].sort_values("Start Date").head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
657,Rebecca,Female,2000-03-05,10:33 AM,46750,11.367,True,Sales
292,Anne,Female,2000-03-07,6:45 AM,44537,18.284,True,Client Services
160,Kathy,Female,2000-03-18,7:26 PM,149563,16.991,True,Finance
682,Deborah,Female,2000-04-23,6:55 PM,105573,5.268,True,Product
92,Linda,Female,2000-05-25,5:45 PM,119009,12.506,True,Business Development

- Assign the Boolean `Series` to a variable for a simpler syntax.

In [12]:
isSenior = employees["Senior Management"]
isSenior.head()

0     True
1     True
2    False
3     True
4     True
Name: Senior Management, dtype: bool

- An existing Boolean column can serve as a filter.

- We can generate a Boolean `Series` using a wide variety of operations (equality, inequality, less than, greater than, inclusion, etc)

In [36]:
import datetime as dt
# Need to convert before this check, but it should only happen once.
# employees["Last Login Time"] = pd.to_datetime(
#     employees["Last Login Time"], format="%H:%M %p"
# ).dt.time
employees[employees["Last Login Time"] < dt.time(12, 0, 0)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

## Filter with More than One Condition (AND)

In [ ]:
# I figured this one out up above!

- Add the `&` operator in between two Boolean `Series` to filter by multiple conditions.
- Add parentheses around the individual `Series` to avoid errors/confusion.

- We can assign the `Series` to variables to make the syntax more readable.
- Variables also remove the need for parentheses.

In [ ]:
is_female = employees["Gender"] == "Female"
is_in_marketing = employees["Team"] == "Marketing"
salary_over_100k = employees["Salary"] > 100000

employees[is_female & is_in_marketing & salary_over_100k].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
98,Tina,Female,2016-06-16,07:47:00,100705,16.961,True,Marketing
140,Shirley,Female,1981-02-28,01:23:00,113850,1.854,False,Marketing
158,Norma,Female,1999-02-28,08:45:00,114412,8.756,True,Marketing
305,Margaret,Female,1993-02-06,01:05:00,125220,3.733,False,Marketing
319,Jacqueline,Female,1981-11-25,03:01:00,145988,18.243,False,Marketing

## Filter with More than One Condition (OR)
- Use the `|` operator in between two Boolean `Series` to filter by *either* condition.

- Let's target employees who are either senior management OR who started before 1990-01-01.

In [33]:
import datetime as dt

if not pd.api.types.is_datetime64_any_dtype(employees["Start Date"]):
  employees["Start Date"] = pd.to_datetime(employees["Start Date"], format="%Y-%m-%d")

isSenior = employees["Senior Management"] == True
startedBefore = employees["Start Date"].dt.date < dt.date(1990,1,1)
employees[isSenior | startedBefore].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal

- Let's look for employees named Robert who work in Client Services OR have a start date after 2016-06-01.

In [37]:
namedRobert = employees["First Name"] == "Robert"
workInCS = employees["Team"] == "Client Services"
startDateCheck = employees["Start Date"].dt.date > dt.date(2016, 6, 1)
employees[(namedRobert & workInCS) | startDateCheck]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
98,Tina,Female,2016-06-16,07:47:00,100705,16.961,True,Marketing
387,Robert,Male,1994-10-29,04:26:00,123294,19.894,False,Client Services
451,Terry,NaN,2016-07-15,12:29:00,140002,19.490,True,Marketing

In [38]:
# Or perhaps they meant this....
employees[namedRobert & (workInCS | startDateCheck)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
387,Robert,Male,1994-10-29,04:26:00,123294,19.894,False,Client Services

## The isin Method
- The `isin` method accepts a collection object like a list, tuple, or `Series`.
- The method returns True for a row if its value is found within the collection.

- Let's say we're targeting employees whose team is Legal, Sales, or Product.

In [40]:
# This is how we would have done it....
legal_team = employees["Team"] == "Legal"
sales_team = employees["Team"] == "Sales"
product_team = employees["Team"] == "Product"

employees[legal_team | sales_team | product_team].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
11,Julie,Female,1997-10-26,03:19:00,102508,12.637,True,Legal
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product

In [ ]:
# but this actually uses .isin, which the completed file didn't

## The isnull and notnull Methods
- The `isnull` method returns True for `NaN` values in a `Series`.
- The `notnull` method returns True for present values in a `Series`.
- The `isna` method is an alias for `isnull`.
- The `notna` method is an alias for `notnull`.

## The between Method
- The `between` method returns True if a `Series` value is found within its range.

## The duplicated Method
- The `duplicated` method returns True if a `Series` value is a duplicate.
- Pandas will mark one occurrence of a repeated value as a non-duplicate.
- Use the `keep` parameter to designate whether to consider the first or last occurrence of a repeated value as the non-duplicate.
- Pass `False` to the `keep` parameter to mark all occurrences of repeated values as duplicates.

- Use the tilde symbol (`~`) to invert a `Series's` values. True will become Falses, and Falses will become Trues.

## The drop_duplicates Method
- The `drop_duplicates` method deletes rows with duplicate values.
- By default, it will remove a row if *all* of its values are shared with another row.
- The `subset` parameter configures the columns to look for duplicate values within.

- Pass a list to `subset` parameter to look for duplicates across multiple columns.

## The where Method
- Like the square brackets, the `where` method accepts a Boolean `Series` to filter the `DataFrame`.
- The resulting `DataFrame` will be of the same length as the original.
- Rows that do not satisfy the filtering criteria will have `NaN`s.
- The `where` method is ideal when you want to preserve the original `DataFrame` structure.

## The query Method
- The `query` method filters a `DataFrame` using a string argument.
- Its argument is a more readable alternative to Boolean filtering.

- Use `and`, `or`, and `not` (or `&`, `|`, `~`) within the expression string.

- Use the `in` and `not in` operators to check inclusion/exclusion.

- Use the `@` prefix to reference local variables.