# The GroupBy Object

In [1]:
import pandas as pd

## The Fortune 1000 Dataset
- The **Fortune 1000** is a listing of the 1000 largest American companies as ranked by Fortune magazine.
- The `DataFrame` includes the company's name, sector, industry, and revenues, profits, and employees.

In [2]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

## The groupby Method
- **Grouping** is a way to organize/categorize/group the data based on a column's values.
- The `groupby` method returns a `DataFrameGroupBy` object.
- The `DataFrameGroupBy` object represents a group/collection of `DataFrame` objects in a dictionary-like structure.
- The `DataFrameGroupBy` object can perform aggregate operations on *each* group within it.

In [5]:
industries = fortune.groupby(by="Industry")
industries.size()

Industry
Advertising, marketing                            2
Aerospace and Defense                            20
Airlines                                          9
Apparel                                          15
Automotive Retailing, Services                   10
                                                 ..
Waste Management                                  5
Wholesalers: Diversified                         25
Wholesalers: Electronics and Office Equipment     8
Wholesalers: Food and Grocery                     6
Wholesalers: Health Care                          6
Length: 73, dtype: int64

## Retrieve Groups and Rows
- The `get_group` method on the `DataFrameGroupBy` object retrieves a nested `DataFrame` belonging to a specific group/category.

In [6]:
industries.get_group("Airlines")

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
67,American Airlines Group,Transportation,Airlines,40990,7610,118500
68,Delta Air Lines,Transportation,Airlines,40704,4526,82949
80,United Continental Holdings,Transportation,Airlines,37864,7340,84000
142,Southwest Airlines,Transportation,Airlines,19820,2181,49583
405,JetBlue Airways,Transportation,Airlines,6416,677,14537
459,Alaska Air Group,Transportation,Airlines,5598,848,13858
709,SkyWest,Transportation,Airlines,3096,118,18300
884,Hawaiian Holdings,Transportation,Airlines,2318,183,5548
933,Spirit Airlines,Transportation,Airlines,2142,317,4326

## Methods on the GroupBy Object
- Use square brackets on the `DataFrameGroupBy` object to extract a column from the original `DataFrame`.
- The resulting `SeriesGroupBy` object will have aggregation methods available on it.
- Pandas will perform the calculation on *every* group within the collection.
- For example, the `sum` method will sum together the revenues for every row by group/category.

In [9]:
industries["Revenue"].sum()

Industry
Advertising, marketing                            22748
Aerospace and Defense                            357940
Airlines                                         158948
Apparel                                           95968
Automotive Retailing, Services                   113823
                                                  ...
Waste Management                                  30454
Wholesalers: Diversified                         176138
Wholesalers: Electronics and Office Equipment    147906
Wholesalers: Food and Grocery                    111774
Wholesalers: Health Care                         444512
Name: Revenue, Length: 73, dtype: int64

- Pass a list to target multiple columns.

In [12]:
industries[["Employees", "Profits"]].mean()

                                                  Employees      Profits
Industry
Advertising, marketing                         62050.000000   774.500000
Aerospace and Defense                          48402.850000  1437.100000
Airlines                                       43511.222222  2644.444444
Apparel                                        23093.133333   549.066667
Automotive Retailing, Services                 17497.400000   255.000000
...                                                     ...          ...
Waste Management                               23839.800000   343.600000
Wholesalers: Diversified                        9353.240000   207.720000
Wholesalers: Electronics and Office Equipment  20832.625000   232.125000
Wholesalers: Food and Grocery                  19317.500000   194.333333
Wholesalers: Health Care                       26000.000000   560.166667

[73 rows x 2 columns]

## The agg Method
- The `agg` method applies different aggregation methods on different columns.
- Invoke the `agg` method directly on the `DataFrameGroupBy` object.
- Pass the method a dictionary where the keys are the columns and the values are the aggregation operations.

In [13]:
industries.agg({"Profits": "sum", "Employees": "size"})

                                               Profits  Employees
Industry
Advertising, marketing                            1549          2
Aerospace and Defense                            28742         20
Airlines                                         23800          9
Apparel                                           8236         15
Automotive Retailing, Services                    2550         10
...                                                ...        ...
Waste Management                                  1718          5
Wholesalers: Diversified                          5193         25
Wholesalers: Electronics and Office Equipment     1857          8
Wholesalers: Food and Grocery                     1166          6
Wholesalers: Health Care                          3361          6

[73 rows x 2 columns]

- Pass a list of operations to compute multiple statistics on the same column at once.

In [14]:
industries.agg({"Profits": ["sum", "mean"], "Employees": "size"})

                                              Profits              Employees
                                                  sum         mean      size
Industry
Advertising, marketing                           1549   774.500000         2
Aerospace and Defense                           28742  1437.100000        20
Airlines                                        23800  2644.444444         9
Apparel                                          8236   549.066667        15
Automotive Retailing, Services                   2550   255.000000        10
...                                               ...          ...       ...
Waste Management                                 1718   343.600000         5
Wholesalers: Diversified                         5193   207.720000        25
Wholesalers: Electronics and Office Equipment    1857   232.125000         8
Wholesalers: Food and Grocery                    1166   194.333333         6
Wholesalers: Health Care                         3361   560.166667         6

[73 rows x 3 columns]

## Grouping by Multiple Columns
- Pass a list of columns to the `groupby` method to group by pairings of values across columns.
- Target a column to retrieve the `SeriesGroupBy` object, then perform an aggregation with a method.
- Pandas will return a `MultiIndex` `Series` where the levels will be the original groups.

In [19]:
multi = fortune.groupby(["Sector", "Industry"])
multi.size()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            20
Apparel              Apparel                                          15
Business Services    Advertising, marketing                            2
                     Diversified Outsourcing Services                 14
                     Education                                         3
                                                                      ..
Transportation       Trucking, Truck Leasing                           9
Wholesalers          Miscellaneous                                     1
                     Wholesalers: Diversified                         25
                     Wholesalers: Electronics and Office Equipment     8
                     Wholesalers: Food and Grocery                     6
Length: 79, dtype: int64

In [20]:
multi["Employees"].sum()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            968057
Apparel              Apparel                                          346397
Business Services    Advertising, marketing                           124100
                     Diversified Outsourcing Services                 708330
                     Education                                         46755
                                                                       ...
Transportation       Trucking, Truck Leasing                          170456
Wholesalers          Miscellaneous                                      9200
                     Wholesalers: Diversified                         233831
                     Wholesalers: Electronics and Office Equipment    166661
                     Wholesalers: Food and Grocery                    115905
Name: Employees, Length: 79, dtype: int64

## Iterating over Groups
- We can iterate over every `DataFrame` in a `DataFrameGroupBy` with a `for` loop.
- Each iteration yields a tuple of `(group_name, group_DataFrame)`.

In [24]:
industries.head() # not sure why this doesn't work as expected

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400
...,...,...,...,...,...,...
951,On Assignment,Business Services,Temporary Help,2077,98,3320
954,Alliance One International,"Food, Beverages & Tobacco",Tobacco,2066,-15,6835
972,Genesee & Wyoming,Transportation,Railroads,2000,225,7500
974,Roadrunner Transportation Systems,Transportation,Transportation and Logistics,1995,48,4502
993,DeVry Education Group,Business Services,Education,1910,140,11770

In [25]:
for name, dataframe in industries:
  print(name)

Advertising, marketing
Aerospace and Defense
Airlines
Apparel
Automotive Retailing, Services
Beverages
Building Materials, Glass
Chemicals
Commercial Banks
Computer Peripherals
Computer Software
Computers, Office Equipment
Construction and Farm Machinery
Diversified Financials
Diversified Outsourcing Services
Education
Electronics, Electrical Equip.
Energy
Engineering, Construction
Entertainment
Financial Data Services
Food Consumer Products
Food Production
Food Services
Food and Drug Stores
Forest and Paper Products
General Merchandisers
Health Care: Insurance and Managed Care
Health Care: Medical Facilities
Health Care: Pharmacy and Other Services
Home Equipment, Furnishings
Homebuilders
Hotels, Casinos, Resorts
Household and Personal Products
Industrial Machinery
Information Technology Services
Insurance: Life, Health (Mutual)
Insurance: Life, Health (stock)
Insurance: Property and Casualty (Mutual)
Insurance: Property and Casualty (Stock)
Internet Services and Retailing
Mail, Package, and Freight Delivery
Medical Products and Equipment
Metals
Mining, Crude-Oil Production
Miscellaneous
Motor Vehicles and Parts
Network and Other Communications Equipment
Oil and Gas Equipment, Services
Packaging, Containers
Petroleum Refining
Pharmaceuticals
Pipelines
Publishing, Printing
Railroads
Real estate
Scientific,Photographic and Control Equipment
Securities
Semiconductors and Other Electronic Components
Specialty Retailers: Apparel
Specialty Retailers: Other
Telecommunications
Temporary Help
Tobacco
Transportation Equipment
Transportation and Logistics
Trucking, Truck Leasing
Utilities: Gas and Electric
Waste Management
Wholesalers: Diversified
Wholesalers: Electronics and Office Equipment
Wholesalers: Food and Grocery
Wholesalers: Health Care

- The `DataFrameGroupBy` object supports the `apply` method (just like a `Series` and a `DataFrame` do).
- The `apply` method invokes a function on every nested `DataFrame` in the `DataFrameGroupBy` object.
- It captures the return values of the functions and collects them in a new `DataFrame` (the return value).

In [32]:
def my_func(industry):
  return industry.sum("Revenue")

def top_two_companies_by_employee_count(sector):
    return sector.nlargest(2, "Employees")

In [33]:
top_two_companies_by_employee_count(fortune)

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
218,Yum Brands,"Hotels, Resturants & Leisure",Food Services,13105,1293,505000

In [34]:
industries.apply(top_two_companies_by_employee_count)

                                                                    Company  \
Industry                                      Rank
Advertising, marketing                        186             Omnicom Group
                                              355         Interpublic Group
Aerospace and Defense                         45        United Technologies
                                              24                     Boeing
Airlines                                      67    American Airlines Group
...                                                                     ...
Wholesalers: Electronics and Office Equipment 64               Ingram Micro
Wholesalers: Food and Grocery                 57                      Sysco
                                              122          US Foods Holding
Wholesalers: Health Care                      5                    McKesson
                                              21            Cardinal Health

                                                                 Sector  \
Industry                                      Rank
Advertising, marketing                        186     Business Services
                                              355     Business Services
Aerospace and Defense                         45    Aerospace & Defense
                                              24    Aerospace & Defense
Airlines                                      67         Transportation
...                                                                 ...
Wholesalers: Electronics and Office Equipment 64            Wholesalers
Wholesalers: Food and Grocery                 57            Wholesalers
                                              122           Wholesalers
Wholesalers: Health Care                      5             Health Care
                                              21            Health Care

                                                    Revenue  Profits  \
Industry                                      Rank
Advertising, marketing                        186     15134     1094
                                              355      7614      455
Aerospace and Defense                         45      61047     7608
                                              24      96114     5176
Airlines                                      67      40990     7610
...                                                     ...      ...
Wholesalers: Electronics and Office Equipment 64      43026      215
Wholesalers: Food and Grocery                 57      48681      687
                                              122     23128      168
Wholesalers: Health Care                      5      181241     1476
                                              21     102531     1215

                                                    Employees
Industry                                      Rank
Advertising, marketing                        186       74900
                                              355       49200
Aerospace and Defense                         45       197200
                                              24       161400
Airlines                                      67       118500
...                                                       ...
Wholesalers: Electronics and Office Equipment 64        27700
Wholesalers: Food and Grocery                 57        51700
                                              122       25000
Wholesalers: Health Care                      5         70400
                                              21        34500

[146 rows x 5 columns]