# Working with Dates and Times

In [1]:
import pandas as pd

## Review of Python's datetime Module
- A module is a file of Python code.
- The `datetime` module is part of Python's standard library, a collection of built-in features.
- The common alias for the `datetime` module is `dt`.

In [2]:
import datetime as dt

- The `datetime` module exports `date`, `time`, and `datetime` classes for representing dates and datetimes.
- The `date` constructor accepts arguments for year, month, and day.
- The `time` constructor accepts arguments for hours, minutes, and seconds.
- The `datetime` constructor accepts arguments for year, month, day, hour, minute, and second.
- The constructors default to 0 for any missing values.

In [4]:
today = dt.date.today()
today

datetime.date(2026, 9, 25)

In [5]:
today.year

2026

In [6]:
type(today)

datetime.date

In [11]:
dt.datetime(1967, 9, 21, 15, 6)

datetime.datetime(1967, 9, 21, 15, 6)

## The dt Attribute
- The `dt` attribute on a `Series` exposes a `DatetimeProperties` object with attributes/methods for working with datetimes.
- The `DatetimeProperties` object has attributes like `day`, `month`, and `year` to reveal information about each date in the `Series`.

In [12]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"])
stocks.head()

        Date  Open  High   Low  Close  Volume
0 1962-01-02  1.48  1.48  1.46   1.46  407940
1 1962-01-03  1.46  1.48  1.46   1.48  305955
2 1962-01-04  1.48  1.48  1.46   1.46  274575
3 1962-01-05  1.46  1.46  1.43   1.43  384405
4 1962-01-08  1.43  1.43  1.39   1.41  572685

In [15]:
stocks["Date"].dt.year.unique()

array([1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972,
       1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983,
       1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994,
       1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026],
      dtype=int32)

- The `day_name` method returns the written day of the week.

In [17]:
stocks["Date"].dt.day_name().head()

0      Tuesday
1    Wednesday
2     Thursday
3       Friday
4       Monday
Name: Date, dtype: str

- Attributes like `is_month_end` and `is_quarter_start` return Boolean `Series`.

In [19]:
# select stocks where the date is the month end
stocks[stocks["Date"].dt.is_month_end].head()

          Date  Open  High   Low  Close   Volume
21  1962-01-31  1.36  1.39  1.36   1.39   800190
40  1962-02-28  1.37  1.37  1.36   1.37   282420
82  1962-04-30  1.24  1.25  1.15   1.16  2455485
104 1962-05-31  1.00  1.02  1.00   1.00  4322595
146 1962-07-31  0.99  1.01  0.99   0.99  2902650

In [ ]:
# This one assumes the start of the fiscal year == start of calendar year
stocks[stocks["Date"].dt.is_quarter_end].head()

          Date  Open  High   Low  Close   Volume
251 1962-12-31  1.01  1.01  1.00   1.00  1098300
440 1963-09-30  1.15  1.16  1.15   1.16   674670
502 1963-12-31  1.28  1.31  1.28   1.30  1820040
564 1964-03-31  1.51  1.52  1.51   1.52  1090455
628 1964-06-30  1.53  1.54  1.53   1.53   307524

## The Timestamp Type
- Pandas has its own `Timestamp` type for modelling a date or datetime.

In [26]:
pd.Timestamp(2902, 1, 1, 4, 5)

Timestamp('2902-01-01 04:05:00')

- The `Timestamp` constructor also accepts `dt.date` and `dt.datetime` objects.
- The `Timestamp` cannot model a time without a day and thus does not accept `dt.time` objects.

In [25]:
pd.Timestamp(dt.date.today())

Timestamp('2026-09-25 00:00:00')

- When we convert a column to `datetime64`, each row actually stores a `Timestamp`.

In [29]:
type(stocks["Date"].iloc[0])

pandas.Timestamp

## Extracting Datetime Rows from a DataFrame
- When generating a Boolean `Series` against a `datetime64` column, you can use either strings, `datetime` objects, or `Timestamp` objects.

In [30]:
stocks[stocks["Date"].between("1995-04-03", "1995-04-11")]

           Date   Open   High    Low  Close    Volume
8369 1995-04-03   9.79   9.93   9.79   9.86   7924914
8370 1995-04-04   9.89   9.95   9.82   9.87   7048366
8371 1995-04-05   9.86  10.01   9.86   9.99   8402727
8372 1995-04-06  10.04  10.07   9.95   9.98   6219516
8373 1995-04-07   9.96  10.13   9.93   9.99  10160007
8374 1995-04-10   9.99  10.23   9.99  10.23   8851670
8375 1995-04-11  10.22  10.34  10.19  10.32  10798904

In [31]:
stocks[stocks["Date"] == dt.datetime(1995, 4, 3)]

           Date  Open  High   Low  Close   Volume
8369 1995-04-03  9.79  9.93  9.79   9.86  7924914

- We can set a column of `datetime` values as the index.
- The `DataFrame` sill store a `DatetimeIndex` object.

In [32]:
date_index = pd.read_csv("ibm.csv", parse_dates=["Date"], index_col="Date").sort_index()
date_index.tail()

              Open    High     Low   Close    Volume
Date
2026-01-26  293.16  296.82  293.14  296.33   3726900
2026-01-27  297.16  297.33  293.27  293.86   2954900
2026-01-28  294.17  295.95  291.26  294.16   5790300
2026-01-29  317.86  319.90  303.47  309.24  10124900
2026-01-30  307.60  307.78  299.73  306.70   5938900

- Use the `iloc` accessor for index position-based extraction.

In [33]:
date_index.iloc[9]

Open           1.45
High           1.45
Low            1.45
Close          1.45
Volume    266730.00
Name: 1962-01-15 00:00:00, dtype: float64

- Use the `loc` accessor for index label-based extraction.
- The accessor accepts strings, `datetime` objects, or `Timestamp` objects.
- Use list slicing to extract a sequence of dates.
- The `truncate` method is another alternative for extracting a range of dates..

In [34]:
date_index.loc["1962-01-02"]

Open           1.48
High           1.48
Low            1.46
Close          1.46
Volume    407940.00
Name: 1962-01-02 00:00:00, dtype: float64

In [ ]:
# this one seems way more useful. Not inclusive of second argument
date_index.loc[pd.Timestamp(1960, 1, 1) : pd.Timestamp(1965, 1, 1)]

            Open  High   Low  Close  Volume
Date
1962-01-02  1.48  1.48  1.46   1.46  407940
1962-01-03  1.46  1.48  1.46   1.48  305955
1962-01-04  1.48  1.48  1.46   1.46  274575
1962-01-05  1.46  1.46  1.43   1.43  384405
1962-01-08  1.43  1.43  1.39   1.41  572685
...          ...   ...   ...    ...     ...
1964-12-24  1.32  1.33  1.32   1.33  213384
1964-12-28  1.33  1.33  1.32   1.32  320076
1964-12-29  1.32  1.32  1.32   1.32  577392
1964-12-30  1.32  1.32  1.31   1.32  414216
1964-12-31  1.32  1.33  1.31   1.31  520908

[756 rows x 5 columns]

- The second argument to `loc` represents the column(s) to target.

In [40]:
date_index.loc["1964-12-28", ["High", "Low"]]

High    1.33
Low     1.32
Name: 1964-12-28 00:00:00, dtype: float64

- Pass a shorter string like `"2025"` or `"2025-03"` to `loc` to select all rows within that year or month.

In [41]:
date_index.loc["2025"]

              Open    High     Low   Close   Volume
Date
2025-01-02  216.23  216.89  212.12  214.40  2579500
2025-01-03  215.00  218.03  215.00  217.04  3872100
2025-01-06  217.38  218.70  215.19  217.06  2846700
2025-01-07  217.72  221.00  217.22  218.32  3299300
2025-01-08  218.27  219.24  215.27  217.56  2619800
...            ...     ...     ...     ...      ...
2025-12-24  303.76  305.15  302.30  304.56  1210600
2025-12-26  304.69  305.75  303.67  305.09  2814700
2025-12-29  304.65  310.00  303.75  305.74  4664500
2025-12-30  306.15  306.24  302.00  302.05  1883700
2025-12-31  301.76  301.85  295.87  296.21  3430100

[250 rows x 5 columns]

In [42]:
date_index.loc["1960" : "1965"]

            Open  High   Low  Close  Volume
Date
1962-01-02  1.48  1.48  1.46   1.46  407940
1962-01-03  1.46  1.48  1.46   1.48  305955
1962-01-04  1.48  1.48  1.46   1.46  274575
1962-01-05  1.46  1.46  1.43   1.43  384405
1962-01-08  1.43  1.43  1.39   1.41  572685
...          ...   ...   ...    ...     ...
1965-12-27  1.61  1.62  1.61   1.61  364008
1965-12-28  1.61  1.61  1.60   1.61  382836
1965-12-29  1.61  1.61  1.60   1.60  320076
1965-12-30  1.60  1.61  1.60   1.61  257316
1965-12-31  1.61  1.61  1.60   1.60  207108

[1008 rows x 5 columns]

In [ ]:
date_index.loc["1995-03"]

             Open   High    Low  Close    Volume
Date
1995-03-01   8.94   9.09   8.94   8.97   8579292
1995-03-02   8.97   9.21   8.97   9.19  10086787
1995-03-03   9.18   9.52   9.16   9.50  23279776
1995-03-06   9.46   9.67   9.46   9.55  21101167
1995-03-07   9.56   9.62   9.44   9.49  14437310
1995-03-08   9.49   9.52   9.34   9.49  12691327
1995-03-09   9.56   9.68   9.56   9.59  13089226
1995-03-10   9.62   9.71   9.56   9.65   9929050
1995-03-13   9.70   9.87   9.70   9.76  14607181
1995-03-14   9.79   9.84   9.70   9.70   9484710
1995-03-15   9.67   9.79   9.67   9.73   7410701
1995-03-16   9.73   9.95   9.71   9.93  11906409
1995-03-17   9.93   9.95   9.83   9.83  12415602
1995-03-20   9.84   9.99   9.82   9.93   7707765
1995-03-21   9.93   9.99   9.77   9.79   8321976
1995-03-22   9.77   9.83   9.67   9.71  10239085
1995-03-23   9.70   9.92   9.70   9.92  11564994
1995-03-24   9.95  10.04   9.93   9.95  10792628
1995-03-27   9.98  10.13   9.98  10.11   8487244
1995-03-28  10.10  10.10  10.02  10.05   5660952
1995-03-29  10.02  10.08   9.82   9.87  12432338
1995-03-30   9.89   9.92   9.73   9.80  12372506
1995-03-31   9.77   9.93   9.68   9.77  10953712

In [ ]:
# strange that these are inclusive!
date_index.loc["1995-03" : "1996-07"]

             Open   High    Low  Close    Volume
Date
1995-03-01   8.94   9.09   8.94   8.97   8579292
1995-03-02   8.97   9.21   8.97   9.19  10086787
1995-03-03   9.18   9.52   9.16   9.50  23279776
1995-03-06   9.46   9.67   9.46   9.55  21101167
1995-03-07   9.56   9.62   9.44   9.49  14437310
...           ...    ...    ...    ...       ...
1996-07-25  11.57  12.50  11.45  12.49  37718342
1996-07-26  12.43  12.55  12.25  12.52  16695834
1996-07-29  12.47  12.72  12.46  12.62  13967029
1996-07-30  12.69  13.02  12.50  12.94  16705875
1996-07-31  12.91  13.12  12.90  12.96  14666175

[360 rows x 5 columns]

## The DateOffset Object
- A `DateOffset` object adds time to a `Timestamp` to arrive at a new `Timestamp`.
- The `DateOffset` constructor accepts `days`, `weeks`, `months`, `years` parameters, and more.
- We can pass a `DateOffset` object to the `freq` parameter of the `pd.date_range` function.

In [46]:
pd.Timestamp.today() + pd.DateOffset(days=3)

Timestamp('2026-09-28 15:54:31.149484')

In [48]:
# also works on indices
date_index.index + pd.DateOffset(
    years=55, months=55, days=100, hours=100, minutes=55, seconds=55
)

DatetimeIndex(['2021-11-14 04:55:55', '2021-11-15 04:55:55',
               '2021-11-16 04:55:55', '2021-11-17 04:55:55',
               '2021-11-20 04:55:55', '2021-11-21 04:55:55',
               '2021-11-22 04:55:55', '2021-11-23 04:55:55',
               '2021-11-24 04:55:55', '2021-11-27 04:55:55',
               ...
               '2085-11-28 04:55:55', '2085-12-02 04:55:55',
               '2085-12-03 04:55:55', '2085-12-04 04:55:55',
               '2085-12-05 04:55:55', '2085-12-08 04:55:55',
               '2085-12-09 04:55:55', '2085-12-10 04:55:55',
               '2085-12-11 04:55:55', '2085-12-12 04:55:55'],
              dtype='datetime64[us]', name='Date', length=16128, freq=None)

## The date_range Function
- The `pd.date_range` function generates a `MultiIndex` of values from a start point to an endpoint.
- We can customize the frequency/gap between each `Timestamp` with the `freq` parameter.
- We can also ask it to generate a certain number of values with the `periods` parameter and either a start or end.

In [49]:
pd.date_range(start="1991-02-06", end=dt.date.today())

DatetimeIndex(['1991-02-06', '1991-02-07', '1991-02-08', '1991-02-09',
               '1991-02-10', '1991-02-11', '1991-02-12', '1991-02-13',
               '1991-02-14', '1991-02-15',
               ...
               '2026-09-16', '2026-09-17', '2026-09-18', '2026-09-19',
               '2026-09-20', '2026-09-21', '2026-09-22', '2026-09-23',
               '2026-09-24', '2026-09-25'],
              dtype='datetime64[us]', length=13016, freq='D')

In [ ]:
# can specify a frequency, 1 day is default
pd.date_range(start="1991-02-06", end=dt.date.today(), freq="100W") # 100 weeks

DatetimeIndex(['1991-02-10', '1993-01-10', '1994-12-11', '1996-11-10',
               '1998-10-11', '2000-09-10', '2002-08-11', '2004-07-11',
               '2006-06-11', '2008-05-11', '2010-04-11', '2012-03-11',
               '2014-02-09', '2016-01-10', '2017-12-10', '2019-11-10',
               '2021-10-10', '2023-09-10', '2025-08-10'],
              dtype='datetime64[us]', freq='100W-SUN')

In [ ]:
# or a number of periods, leaving out the start or end date
pd.date_range(end="1991-04-12", freq="7D", periods=200) # 7 days

DatetimeIndex(['1987-06-19', '1987-06-26', '1987-07-03', '1987-07-10',
               '1987-07-17', '1987-07-24', '1987-07-31', '1987-08-07',
               '1987-08-14', '1987-08-21',
               ...
               '1991-02-08', '1991-02-15', '1991-02-22', '1991-03-01',
               '1991-03-08', '1991-03-15', '1991-03-22', '1991-03-29',
               '1991-04-05', '1991-04-12'],
              dtype='datetime64[us]', length=200, freq='7D')

- Let's extract all of the rows that fell on a given date each year.

In [55]:
one_hundred_fridays = pd.date_range(end="2026-09-25", freq="7D", periods=100)
one_hundred_fridays

DatetimeIndex(['2024-11-01', '2024-11-08', '2024-11-15', '2024-11-22',
               '2024-11-29', '2024-12-06', '2024-12-13', '2024-12-20',
               '2024-12-27', '2025-01-03', '2025-01-10', '2025-01-17',
               '2025-01-24', '2025-01-31', '2025-02-07', '2025-02-14',
               '2025-02-21', '2025-02-28', '2025-03-07', '2025-03-14',
               '2025-03-21', '2025-03-28', '2025-04-04', '2025-04-11',
               '2025-04-18', '2025-04-25', '2025-05-02', '2025-05-09',
               '2025-05-16', '2025-05-23', '2025-05-30', '2025-06-06',
               '2025-06-13', '2025-06-20', '2025-06-27', '2025-07-04',
               '2025-07-11', '2025-07-18', '2025-07-25', '2025-08-01',
               '2025-08-08', '2025-08-15', '2025-08-22', '2025-08-29',
               '2025-09-05', '2025-09-12', '2025-09-19', '2025-09-26',
               '2025-10-03', '2025-10-10', '2025-10-17', '2025-10-24',
               '2025-10-31', '2025-11-07', '2025-11-14', '2025-11-21',
               '2025-11-28', '2025-12-05', '2025-12-12', '2025-12-19',
               '2025-12-26', '2026-01-02', '2026-01-09', '2026-01-16',
               '2026-01-23', '2026-01-30', '2026-02-06', '2026-02-13',
               '2026-02-20', '2026-02-27', '2026-03-06', '2026-03-13',
               '2026-03-20', '2026-03-27', '2026-04-03', '2026-04-10',
               '2026-04-17', '2026-04-24', '2026-05-01', '2026-05-08',
               '2026-05-15', '2026-05-22', '2026-05-29', '2026-06-05',
               '2026-06-12', '2026-06-19', '2026-06-26', '2026-07-03',
               '2026-07-10', '2026-07-17', '2026-07-24', '2026-07-31',
               '2026-08-07', '2026-08-14', '2026-08-21', '2026-08-28',
               '2026-09-04', '2026-09-11', '2026-09-18', '2026-09-25'],
              dtype='datetime64[us]', freq='7D')

In [58]:
date_index[date_index.index.isin(one_hundred_fridays)]

              Open    High     Low   Close   Volume
Date
2024-11-01  200.95  202.96  200.61  201.42  3334100
2024-11-08  207.13  209.59  205.80  206.71  3201000
2024-11-15  202.23  203.24  198.93  199.83  3986500
2024-11-22  217.72  221.48  215.33  217.35  5320700
2024-11-29  222.01  224.56  221.47  221.68  2640300
...            ...     ...     ...     ...      ...
2026-01-02  297.56  297.57  289.00  291.50  4662800
2026-01-09  302.61  307.00  302.00  304.22  2718800
2026-01-16  301.00  307.45  300.78  305.67  6199600
2026-01-23  294.07  294.34  289.79  292.44  3298400
2026-01-30  307.60  307.78  299.73  306.70  5938900

[64 rows x 5 columns]

## Specialized Date Offsets
- Pandas nests more specialized date offsets in `pd.tseries.offsets`.
- The offsets represent custom spans of time (month end, quarter end, year begin, etc).
- Use `+` to move time forward into the future.
- Use `-` to move time backward into the past.

In [59]:
date_index.index + pd.tseries.offsets.MonthEnd()

DatetimeIndex(['1962-01-31', '1962-01-31', '1962-01-31', '1962-01-31',
               '1962-01-31', '1962-01-31', '1962-01-31', '1962-01-31',
               '1962-01-31', '1962-01-31',
               ...
               '2026-01-31', '2026-01-31', '2026-01-31', '2026-01-31',
               '2026-01-31', '2026-01-31', '2026-01-31', '2026-01-31',
               '2026-01-31', '2026-01-31'],
              dtype='datetime64[us]', name='Date', length=16128, freq=None)

In [ ]:
# ah, now we can set fiscal year start
date_index.index + pd.tseries.offsets.QuarterBegin(startingMonth=4)

DatetimeIndex(['1962-04-01', '1962-04-01', '1962-04-01', '1962-04-01',
               '1962-04-01', '1962-04-01', '1962-04-01', '1962-04-01',
               '1962-04-01', '1962-04-01',
               ...
               '2026-04-01', '2026-04-01', '2026-04-01', '2026-04-01',
               '2026-04-01', '2026-04-01', '2026-04-01', '2026-04-01',
               '2026-04-01', '2026-04-01'],
              dtype='datetime64[us]', name='Date', length=16128, freq=None)

In [ ]:
date_index.index + pd.tseries.offsets.YearBegin()

DatetimeIndex(['1963-01-01', '1963-01-01', '1963-01-01', '1963-01-01',
               '1963-01-01', '1963-01-01', '1963-01-01', '1963-01-01',
               '1963-01-01', '1963-01-01',
               ...
               '2027-01-01', '2027-01-01', '2027-01-01', '2027-01-01',
               '2027-01-01', '2027-01-01', '2027-01-01', '2027-01-01',
               '2027-01-01', '2027-01-01'],
              dtype='datetime64[us]', name='Date', length=16128, freq=None)

## Timedeltas
- A `Timedelta` is a pandas object that represents a duration (an amount of time).
- Subtracting two `Timestamp` objects will yield a `Timedelta` object (this applies to subtracting a `Series` from another `Series`).
- The `Timedelta` constructor accepts parameters for time as well as string descriptions.

In [63]:
pd.Timestamp("2026-03-31 12:30:48") - pd.Timestamp("2026-03-20 19:25:59")

Timedelta('10 days 17:04:49')

In [64]:
pd.Timedelta(days=3, hours=2, minutes=5)

Timedelta('3 days 02:05:00')

In [65]:
ecommerce = pd.read_csv(
    "ecommerce.csv",
    index_col="ID",
    parse_dates=["order_date", "delivery_date"],
    date_format="%m/%d/%y",
)

ecommerce.head()

   order_date delivery_date
ID
1  1998-05-24    1999-02-05
2  1992-04-22    1998-03-06
4  1991-02-10    1992-08-26
5  1992-07-21    1997-11-20
7  1993-09-02    1998-06-10

In [ ]:
ecommerce["delivery_time"] = ecommerce["delivery_date"] - ecommerce["order_date"]
ecommerce.head() # but why days?

   order_date delivery_date delivery_time
ID
1  1998-05-24    1999-02-05      257 days
2  1992-04-22    1998-03-06     2144 days
4  1991-02-10    1992-08-26      563 days
5  1992-07-21    1997-11-20     1948 days
7  1993-09-02    1998-06-10     1742 days